/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{svelte,js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-secondary-container": "#626267",
        "tertiary-container": "#008733",
        "on-tertiary-container": "#f7fff2",
        "secondary-fixed-dim": "#c6c6cb",
        "on-error": "#ffffff",
        "surface-variant": "#e2e2e7",
        "on-primary-container": "#fefcff",
        "on-surface": "#1a1c1f",
        "surface-container-low": "#f3f3f8",
        "surface-container-high": "#e8e8ed",
        "surface-container-lowest": "#ffffff",
        "on-tertiary-fixed-variant": "#00531c",
        "surface-container": "#ededf2",
        "on-primary": "#ffffff",
        "error-container": "#ffdad6",
        "surface-bright": "#f9f9fe",
        "on-background": "#1a1c1f",
        "on-secondary-fixed-variant": "#46464b",
        "outline-variant": "#c1c6d7",
        "on-error-container": "#93000a",
        "secondary-container": "#e0dfe4",
        "outline": "#717786",
        "surface": "#f9f9fe",
        "surface-tint": "#005bc1",
        "error": "#ba1a1a",
        "tertiary-fixed-dim": "#53e16f",
        "primary-fixed-dim": "#adc6ff",
        "secondary-fixed": "#e3e2e7",
        "on-surface-variant": "#414755",
        "inverse-surface": "#2e3034",
        "inverse-on-surface": "#f0f0f5",
        "background": "#f9f9fe",
        "surface-dim": "#d9dade",
        "primary": "#0058bc",
        "on-secondary": "#ffffff",
        "on-tertiary-fixed": "#002107",
        "inverse-primary": "#adc6ff",
        "primary-container": "#0070eb",
        "on-tertiary": "#ffffff",
        "tertiary-fixed": "#72fe88",
        "primary-fixed": "#d8e2ff",
        "on-primary-fixed-variant": "#004493",
        "on-secondary-fixed": "#1a1b1f",
        "on-primary-fixed": "#001a41",
        "tertiary": "#006b27",
        "secondary": "#5d5e63",
        "surface-container-highest": "#e2e2e7"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "xs": "8px",
        "base": "4px",
        "xl": "32px",
        "md": "16px",
        "margin-desktop": "40px",
        "gutter": "16px",
        "lg": "24px",
        "margin-mobile": "16px",
        "sm": "12px"
      },
      fontFamily: {
        "body-lg": ["Inter", "Noto Sans JP"],
        "body-sm": ["Inter", "Noto Sans JP"],
        "label-caps": ["Inter", "Noto Sans JP"],
        "label-badge": ["Inter", "Noto Sans JP"],
        "headline-md": ["Inter", "Noto Sans JP"],
        "headline-lg": ["Inter", "Noto Sans JP"],
        "headline-lg-mobile": ["Inter", "Noto Sans JP"]
      },
      fontSize: {
        "body-lg": ["17px", {"lineHeight": "22px", "letterSpacing": "-0.01em", "fontWeight": "400"}],
        "body-sm": ["15px", {"lineHeight": "20px", "fontWeight": "400"}],
        "label-caps": ["12px", {"lineHeight": "16px", "letterSpacing": "0.05em", "fontWeight": "600"}],
        "label-badge": ["13px", {"lineHeight": "18px", "fontWeight": "500"}],
        "headline-md": ["22px", {"lineHeight": "28px", "letterSpacing": "-0.01em", "fontWeight": "600"}],
        "headline-lg": ["34px", {"lineHeight": "41px", "letterSpacing": "-0.02em", "fontWeight": "700"}],
        "headline-lg-mobile": ["28px", {"lineHeight": "34px", "letterSpacing": "-0.01em", "fontWeight": "700"}]
      }
    },
  },
  plugins: [],
}
